services:
  postgresql:
    image: postgres:11.15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7432:5432"
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: on-failure
    command: "redis-server --save 60 1 --appendonly yes --loglevel warning"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    ports:
      - "7379:6379"
    networks:
      - internal

  orkes-server:
    container_name: orkes-server
    image: ghcr.io/ibrahimawadhamid/orkes-conductor-community:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/postgres
      - conductor.redis-lock.serverAddress=redis://redis:6379
      - conductor.redis.hosts=redis:6379:us-east-1c
      - conductor.queue.type=redis_standalone
      - conductor.db.type=redis_standalone
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
      - postgresql
    ports:
      - "9090:8080"
    networks:
      - internal

networks:
  internal:
